PUT http://localhost:3001/api/objave/64173bd00f3d75dd0f79c191
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1ajIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RVc2VyIiwiaWQiOiI2NDE1Y2YwYmNhNTNlNzQ3OTRmOGZkOWUiLCJpYXQiOjE2NzkyNDQyNjJ9.tiuXpri8ZbacbUEbGOOwmKJEDeLcHoxF3OUHCadhfbM

{
  "sadrzaj": "OBJAVAAZURIRANA",
  "datum":	"2023-03-19T16:35:37.356Z",
  "likeovi": [],
  "komentari": []
}