PUT http://localhost:3001/api/objave/64232638870cfd969b452580
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6IjY0MjMxYTFkODcwY2ZkOTY5YjQ1MjQ4MSIsImlhdCI6MTY4MDEwODg2OX0.9N6O1nM-SeduP31oqxzpJ1C2o41rTJ1qqy3SUGNSXWE

{
  "sadrzaj": "OBJAVAAZURIRANA",
  "datum":	"2023-03-19T16:35:37.356Z",
  "likeovi": [],
  "komentari": []
}