POST http://localhost:3001/api/objave
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RVc2VyIiwiaWQiOiI2NDFiMmFhMzJmNThmYTkwNDRiOGNjOTciLCJpYXQiOjE2Nzk1MDIwMDR9.ZQW9EYFM7ZH8mAFykcdvp2yIdX24fnhHGyeDO4BU-Q8

{
  "sadrzaj": "Objava",
  "korisnikId": "641b2aa32f58fa9044b8cc97"
}