POST http://localhost:3001/api/komentari
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RVc2VyIiwiaWQiOiI2NDFiMmFhMzJmNThmYTkwNDRiOGNjOTciLCJpYXQiOjE2Nzk1MDI0Nzl9.XIwxxVpFewNEITzzll_3aKkHYV53M7_G1JKyDliPgek

{
  "sadrzaj": "KOMENTAR",
  "objava": "641b2acd2f58fa9044b8cc9a",
  "korisnikId": "641b2aa32f58fa9044b8cc97"
}