DELETE http://localhost:3001/api/objave/6423086a459ae288898f31d8
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6IjY0MjMwODM4NDU5YWUyODg4OThmMzFkNCIsImlhdCI6MTY4MDAxODYxNn0.f8rjBTIuQ-Ly1piLJ02_S_Kx2AflD_tpEJhJcH_2RnM