DELETE http://localhost:3001/api/objave/6417426784720c754a41d846
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RVc2VyIiwiaWQiOiI2NDE3NDIwZDg0NzIwYzc1NGE0MWQ4NDIiLCJpYXQiOjE2NzkyNDY0NTB9.h89-yeBCZDqsPOqinIUVddhqDj7AwSrAMbCIVSespqY
korisnikiD: 6417420d84720c754a41d842